# Form implementation generated from reading ui file '/Users/kevin/Projects/soundsep2/soundsep/ui/splash.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashPage(object):
    def setupUi(self, SplashPage):
        SplashPage.setObjectName("SplashPage")
        SplashPage.resize(934, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SplashPage.sizePolicy().hasHeightForWidth())
        SplashPage.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/linux/512.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SplashPage.setWindowIcon(icon)
        SplashPage.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(SplashPage)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(SplashPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/assets/icons/linux/256.png"))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(55, 63, 109);\n"
"}")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(SplashPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.createProjectButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.createProjectButton.setFont(font)
        self.createProjectButton.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 73, 181);\n"
"    font-size: 20pt;\n"
"    padding: 10px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 8, 127);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.createProjectButton.setObjectName("createProjectButton")
        self.verticalLayout_2.addWidget(self.createProjectButton)
        self.reopenProjectButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.reopenProjectButton.setFont(font)
        self.reopenProjectButton.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 73, 181);\n"
"    font-size: 20pt;\n"
"    padding: 10px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 8, 127);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.reopenProjectButton.setObjectName("reopenProjectButton")
        self.verticalLayout_2.addWidget(self.reopenProjectButton)
        self.openProjectButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.openProjectButton.setFont(font)
        self.openProjectButton.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 73, 181);\n"
"    font-size: 20pt;\n"
"    padding: 10px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 8, 127);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.openProjectButton.setObjectName("openProjectButton")
        self.verticalLayout_2.addWidget(self.openProjectButton)
        self.debugProjectButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.debugProjectButton.setFont(font)
        self.debugProjectButton.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 73, 181);\n"
"    font-size: 20pt;\n"
"    padding: 10px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 8, 127);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.debugProjectButton.setObjectName("debugProjectButton")
        self.verticalLayout_2.addWidget(self.debugProjectButton)
        self.exitButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 73, 181);\n"
"    font-size: 20pt;\n"
"    padding: 10px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(0, 8, 127);\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_2.addWidget(self.exitButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(SplashPage)
        QtCore.QMetaObject.connectSlotsByName(SplashPage)

    def retranslateUi(self, SplashPage):
        _translate = QtCore.QCoreApplication.translate
        SplashPage.setWindowTitle(_translate("SplashPage", "SoundSep"))
        self.label_2.setText(_translate("SplashPage", "SoundSep 2"))
        self.createProjectButton.setToolTip(_translate("SplashPage", "<html><head/><body><p>Create a new project from an audio folder</p></body></html>"))
        self.createProjectButton.setText(_translate("SplashPage", "Create project"))
        self.reopenProjectButton.setToolTip(_translate("SplashPage", "<html><head/><body><p>Reopen the last project</p></body></html>"))
        self.reopenProjectButton.setText(_translate("SplashPage", "Reopen last project"))
        self.openProjectButton.setToolTip(_translate("SplashPage", "<html><head/><body><p>Open an existing project by seleting a folder with a soundsep.yaml file</p></body></html>"))
        self.openProjectButton.setText(_translate("SplashPage", "Open existing project..."))
        self.debugProjectButton.setText(_translate("SplashPage", "Debug project files"))
        self.exitButton.setText(_translate("SplashPage", "Exit"))
